build: false

image: Visual Studio 2019

environment:

  SQLSERVER_ENV_SQLSERVER_HOST: localhost
  SQLSERVER_ENV_SQLSERVER_PORT: 1433
  SQLSERVER_ENV_SQLSERVER_USER: sa
  SQLSERVER_ENV_SQLSERVER_PASSWORD: Password12!
  SQLSERVER_ENV_SQLSERVER_DATABASE: qatrackdb

  matrix:
      #- PYTHON: "C:\\Python34"
      #- PYTHON: "C:\\Python34-x64"
      #- PYTHON: "C:\\Python35"
      #- PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python39"
      #- PYTHON: "C:\\Python36-x64"

cache:
  - '%LOCALAPPDATA%\pip\Cache'

init:
  - net start MSSQL$SQL2019
  - "ECHO %PYTHON%"

install:
  - choco install googlechrome  --ignore-checksums
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - cmd: copy /Y deploy\win\appveyor_mssql.py qatrack\local_settings.py
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements\win.txt

build_script:
    #- ps: deploy\sqlserver.ps1 SQL2008R2SP2
  - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE qatrackdb" -d "master"

test_script:
  - python manage.py migrate
  - pytest -x -m "not selenium"

